name: ClearLog
version: '1.0-SNAPSHOT'
main: cn.mtpixel.clearlog.ClearLog
api-version: '1.13'
authors: [ xianbei235 ]
description: 定时清理服务器垃圾日志文件-懒人低配服务器必备
website: https://github.com/xianbei234
